/* Autogenerated by hxtools bin2c */
#ifndef RESOURCES_ICONS_H
#define RESOURCES_ICONS_H 1

class wxBitmap;

extern "C" void bin2c_init_RESOURCES_ICONS_H(void);
extern wxBitmap *bin2c_box_64x64_png;
extern wxBitmap *bin2c_cpu_png;
extern wxBitmap *bin2c_nice_idle_png;
extern wxBitmap *bin2c_nice_killed_png;
extern wxBitmap *bin2c_nice_png;
extern wxBitmap *bin2c_nice_running_png;
extern wxBitmap *bin2c_nice_sleeping_png;
extern wxBitmap *bin2c_nice_stopped_png;
extern wxBitmap *bin2c_nice_waiting_png;
extern wxBitmap *bin2c_nice_zombie_png;
extern wxBitmap *bin2c_normal_idle_png;
extern wxBitmap *bin2c_normal_killed_png;
extern wxBitmap *bin2c_normal_png;
extern wxBitmap *bin2c_normal_running_png;
extern wxBitmap *bin2c_normal_sleeping_png;
extern wxBitmap *bin2c_normal_stopped_png;
extern wxBitmap *bin2c_normal_waiting_png;
extern wxBitmap *bin2c_normal_zombie_png;
extern wxBitmap *bin2c_not_nice_idle_png;
extern wxBitmap *bin2c_not_nice_killed_png;
extern wxBitmap *bin2c_not_nice_png;
extern wxBitmap *bin2c_not_nice_running_png;
extern wxBitmap *bin2c_not_nice_sleeping_png;
extern wxBitmap *bin2c_not_nice_stopped_png;
extern wxBitmap *bin2c_not_nice_waiting_png;
extern wxBitmap *bin2c_not_nice_zombie_png;
extern wxBitmap *bin2c_nut_64x64_png;
extern wxBitmap *bin2c_ram_png;
extern wxBitmap *bin2c_realtime_idle_png;
extern wxBitmap *bin2c_realtime_killed_png;
extern wxBitmap *bin2c_realtime_png;
extern wxBitmap *bin2c_realtime_running_png;
extern wxBitmap *bin2c_realtime_sleeping_png;
extern wxBitmap *bin2c_realtime_stopped_png;
extern wxBitmap *bin2c_realtime_waiting_png;
extern wxBitmap *bin2c_realtime_zombie_png;
extern wxBitmap *bin2c_ua_64x43_png;
extern wxBitmap *bin2c_wxwidgets_logo_64x48_png;


#endif /* RESOURCES_ICONS_H */
