.TH declone 1 "2008-02-06" "hxtools" "hxtools"
.SH Name
declone \(em break hardlinks
.SH Syntax
\fBdeclone\fP \fIfile\fP...
.SH Description
Breaks a hard link as created by \fBln\fP(1) or \fBhardlink\fP(1).
This program makes a copy of the file's contents, the ownership information
and standard permissions. It does not copy ACLs or SELinux contexts.
.SH Example
.nf
$ ln GNUmakefile new1
$ ln GNUmakefile new2
$ ls -li GNUmakefile new1 new2
-rw-r--r--  3 jengelh users 2687 May 27 23:11 GNUmakefile
-rw-r--r--  3 jengelh users 2687 May 27 23:11 new1
-rw-r--r--  3 jengelh users 2687 May 27 23:11 new2
$ declone new2
* new2
$ ls -li GNUmakefile new1 new2
-rw-r--r--  2 jengelh users 2687 May 27 23:11 GNUmakefile
-rw-r--r--  2 jengelh users 2687 May 27 23:11 new1
-rw-r--r--  1 jengelh users 2687 May 28 09:10 new2
.fi
.SH See also
\fBhxtools\fP(7)
