.TH mod2opus 1 "2017-01-13" "hxtools" "hxtools"
.SH Name
mod2opus \(em wrapper for tracker module/MIDI to Opus transcoding
.SH Syntax
\fBmod2opus\fP \fIfile\fP...
.SH Description
Most if not all mobile players ("MP3 player", "smartphone") still
cannot do tracker modules or MIDI, but need a regular premixed file.
.PP
This program wrapper converts such files (.mod, .xm, .it, etc.) to
Opus using Timidity++ or XMP. (For MIDI, timidity's presence is
required.)
.SH See also
\fBhxtools\fP(7)
