.TH psthreads 1 "2009-10-10" "hxtools" "hxtools"
.SH Name
psthreads \(em ps-like program to display threads and with UTF-8 tree
.SH Syntax
\fBpsthreads\fP
psthreads offers no options.
.SH Description
psthreads shows both threads and processes as a task forest, effectively doing
what `ps afmx` refuses to do. Thread links are shown with green line-drawing
characters, process links with brown.
.SH See also
\fBhxtools\fP(7)
