.TH qtar 1 "2013-08-06" "hxtools" "hxtools"
.SH Name
qtar \(em a somewhat shorter tar invocation
.SH Syntax
\fBqtar\fP [\fB\-x\fP] [\fB\-\-ext\fP|\fB\-\-svn\fP] \fIarchive_file\fP [\fItar-options\fP...]
\fIfiles\fP...
.SH Options
.TP
\fB\-x\fP
Exclude SCM directories like "CVS", ".svn", ".hg" and ".git".
.TP
\fB\-\-ext\fP
Sort files by extension
.TP
\fB\-\-svn\fP
Sort files such that file.c and .svn/file.c are next to each other, to yield
better compression of SVN checkout tar archives where the .svn file is often
a copy of the former.
.SH See also
\fBhxtools\fP(7)
