#!/bin/bash
# SPDX-License-Identifier: MIT
#
#	recursive_lower
#	written by Jan Engelhardt, 2004-2007

descend_into()
{
	for src in "$@"; do
		dest="`echo -en \"$src\" | tr A-Z a-z`";
		mv "$src" "$id" && \
		mv "$id" "$dest";
		echo "$src" "->" "$dest";
		if [ -d "$src" -o -d "$dest" ]; then
			descend_into "$dest"/*;
		fi;
	done;
	return;
}

id=`mktemp -u .tmp.$$.XXXXXXXX`;
descend_into "$@";
